# version : "3.3"
# services : 
#   web : 
#     build :
#       context : .
#     ports : 
#       - "8000:8000"


services : 
  web : 
    image : "muhammadrahimharoon/notes-app:latest"
    ports : 
      - "8000:8000"
